<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ApplicationAssistant.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
    <PackageReference Include="QuestPDF" Version="2025.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationAssistant.AI\ApplicationAssistant.AI.csproj" />
  </ItemGroup>
</Project>
